const mongoose = require("mongoose");

const CoursesSchema = new mongoose.Schema({
  // sid: {
  //   type: Number,
  //   required: true,
  // },
  coursename:{
    type:String,
    required:true,
  },
  coursecode: {
    type: String,
    required: true,
  },
  courseHtag: {
    type: String,
    required: true,
  },
  coursecategory: {
    type: String,
    required: true,
  },
  coursetype: [{
    type: String,
    required: true,
  }],
  courseregid: {
    type: String,
    
  },
  rating: {
    type: Number,
    
  },
  coursereview: {
    type: String,
    
  },
  coursereviewurl: {
    type: String,
    
  },
  coursescheduletimezone: {
    type: String,
    
  },
  status: {
    type: String,
    required: true,
  },
  countrymetatitle: {
    type: String,
    
  },
  countrymetadesc: {
    type: String,
    
  },
  citymetatitle: {
    type: String,
    
  },
  citymetadesc: {
    type: String,
    
  },
  studymaterial:{
    type:String,
    // required:true,
  },
  courseagenda:{
    type:String,
    // required:true,
  },
  courseimage:{
    type:String,
    // required:true,
  },
  bannerimage:{
    type:String,
    // required:true,
  },
  bannerimageurl:{
    type:String,
    
  },
  companyimage:{
    type:String,
    
  },
  certificateimage:{
    type:String,
    
  },
  onlinetraining:{
    key1:{
      type:String,
    },
    key2:{
      type:String,
    },
    key3:{
      type:String,
    },
    key4:{
      type:String,
    },
    key5:{
      type:String,
    },
    key6:{
      type:String,
    },
    key7:{
      type:String,
    },
    key8:{
      type:String,
    }
  },
  lvctraining:{
    key1:{
      type:String,
    },
    key2:{
      type:String,
    },
    key3:{
      type:String,
    },
    key4:{
      type:String,
    },
    key5:{
      type:String,
    },
    key6:{
      type:String,
    },
    key7:{
      type:String,
    },
    key8:{
      type:String,
    }
  },
  classroomtraining:{
    key1:{
      type:String,
    },
    key2:{
      type:String,
    },
    key3:{
      type:String,
    },
    key4:{
      type:String,
    },
    key5:{
      type:String,
    },
    key6:{
      type:String,
    },
    key7:{
      type:String,
    },
    key8:{
      type:String,
    }
  },
  generalqs:{
    type:String,
  },
  generalans:{
    a1:{
      type:String,
    },
    a2:{
      type:String,
    },
    a3:{
      type:String,
    },
  },
  course_desc:{
    q1:{
      type:String,
    },
    a1:{
      type:String,
    },
    q2:{
      type:String,
    },
    a2:{
      type:String,
    },
    q3:{
      type:String,
    },
    a3:{
      type:String,
    },
    q4:{
      type:String,
    },
    a4:{
      type:String,
    },
  },
  course_content:{
    module1:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module2:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module3:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module4:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module5:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module6:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module7:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module8:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module9:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    },
    module10:{
      name:{
        type:String,
      },
      topic1:{
        type:String,
      },
      videolink1:{
        type:String,
      },
      topic2:{
        type:String,
      },
      videolink2:{
        type:String,
      },
      topic3:{
        type:String,
      },
      videolink3:{
        type:String,
      },
      topic4:{
        type:String,
      },
      videolink4:{
        type:String,
      },
      topic5:{
        type:String,
      },
      videolink5:{
        type:String,
      },
      topic6:{
        type:String,
      },
      videolink6:{
        type:String,
      },
      topic7:{
        type:String,
      },
      videolink7:{
        type:String,
      },
      topic8:{
        type:String,
      },
      videolink8:{
        type:String,
      },
      topic9:{
        type:String,
      },
      videolink9:{
        type:String,
      },
      topic10:{
        type:String,
      },
      videolink10:{
        type:String,
      },
      topic11:{
        type:String,
      },
      videolink11:{
        type:String,
      },
      topic12:{
        type:String,
      },
      videolink12:{
        type:String,
      },
      topic13:{
        type:String,
      },
      videolink13:{
        type:String,
      },
      topic14:{
        type:String,
      },
      videolink14:{
        type:String,
      },
      topic15:{
        type:String,
      },
      videolink15:{
        type:String,
      },
      topic16:{
        type:String,
      },
      videolink16:{
        type:String,
      },
      topic17:{
        type:String,
      },
      videolink17:{
        type:String,
      },
      topic18:{
        type:String,
      },
      videolink18:{
        type:String,
      },
      topic19:{
        type:String,
      },
      videolink19:{
        type:String,
      },
      topic20:{
        type:String,
      },
      videolink20:{
        type:String,
      },
    }
  },
  examdesc:{
    q1:{
      type:String,
    },
    a1:{
      type:String,
    },
    q2:{
      type:String,
    },
    a2:{
      type:String,
    },
    q3:{
      type:String,
    },
    a3:{
      type:String,
    },
    q4:{
      type:String,
    },
    a4:{
      type:String,
    },
    q5:{
      type:String,
    },
    a5:{
      type:String,
    },
    q6:{
      type:String,
    },
    a6:{
      type:String,
    },
    q7:{
      type:String,
    },
    a7:{
      type:String,
    },
    q8:{
      type:String,
    },
    a8:{
      type:String,
    },
    q9:{
      type:String,
    },
    a9:{
      type:String,
    },
    q10:{
      type:String,
    },
    a10:{
      type:String,
    },
    q11:{
      type:String,
    },
    a11:{
      type:String,
    },
    q12:{
      type:String,
    },
    a12:{
      type:String,
    },
    q13:{
      type:String,
    },
    a13:{
      type:String,
    },
    q14:{
      type:String,
    },
    a14:{
      type:String,
    },
    q15:{
      type:String,
    },
    a15:{
      type:String,
    },
    q16:{
      type:String,
    },
    a16:{
      type:String,
    },
    q17:{
      type:String,
    },
    a17:{
      type:String,
    },
    q18:{
      type:String,
    },
    a18:{
      type:String,
    },
    q19:{
      type:String,
    },
    a19:{
      type:String,
    },
    q20:{
      type:String,
    },
    a20:{
      type:String,
    }
  },
  faq:{
    q1:{
      type:String,
    },
    a1:{
      type:String,
    },
    q2:{
      type:String,
    },
    a2:{
      type:String,
    },
    q3:{
      type:String,
    },
    a3:{
      type:String,
    },
    q4:{
      type:String,
    },
    a4:{
      type:String,
    },
    q5:{
      type:String,
    },
    a5:{
      type:String,
    },
    q6:{
      type:String,
    },
    a6:{
      type:String,
    },
    q7:{
      type:String,
    },
    a7:{
      type:String,
    },
    q8:{
      type:String,
    },
    a8:{
      type:String,
    },
    q9:{
      type:String,
    },
    a9:{
      type:String,
    },
    q10:{
      type:String,
    },
    a10:{
      type:String,
    },
    q11:{
      type:String,
    },
    a11:{
      type:String,
    },
    q12:{
      type:String,
    },
    a12:{
      type:String,
    },
    q13:{
      type:String,
    },
    a13:{
      type:String,
    },
    q14:{
      type:String,
    },
    a14:{
      type:String,
    },
    q15:{
      type:String,
    },
    a15:{
      type:String,
    },
    q16:{
      type:String,
    },
    a16:{
      type:String,
    },
    q17:{
      type:String,
    },
    a17:{
      type:String,
    },
    q18:{
      type:String,
    },
    a18:{
      type:String,
    },
    q19:{
      type:String,
    },
    a19:{
      type:String,
    },
    q20:{
      type:String,
    },
    a20:{
      type:String,
    }
  },
  whychoose:{
    ycq1:{
      type:String,
    },
    yca1:{
      type:String,
    },
    ycq2:{
      type:String,
    },
    yca2:{
      type:String,
    },
    ycq3:{
      type:String,
    },
    yca3:{
      type:String,
    },
    ycq4:{
      type:String,
    },
    yca4:{
      type:String,
    },
  },
  course_key_points:{
    title:{
      type:String,
    },
    key1:{
      type:String,
    },
    key2:{
      type:String,
    },
    key3:{
      type:String,
    },
    key4:{
      type:String,
    },
    key5:{
      type:String,
    },
    key6:{
      type:String,
    }
  },
  course_info:{
    type:String,
  },
  course_slug:{
    type:String,
    required:true,
  },
  disclaimer:{
    type:String,
  },
  checkbox_status:{
    type:String,
    default:'False',
  },
  formbox_title:{
    type:String,
  },
  
});

module.exports = new mongoose.model("Courses", CoursesSchema);
